#!/usr/bin/env bash
set -eo pipefail

function usage {
    cat <<EOF
Manage infrastructure for the Identity Management framework.
Run an Aries agent with below options.
Usage:
    clean:
        Cleanup docker related files, needs to be done periodically in development because of unused volumes.
    setup:
        Instantiate all infrastructure related services.
    teardown:
        Stop all infrastructure related services.
    restart:
        Runs 'teardown' and then 'setup', restarting the infrastructure.
    help:
        Print the usage.
EOF
}

cmd=$1

if [[ $cmd == "clean" ]]; then
    printf "Cleaning Docker ...\n\n"
    docker system prune
elif [[ $cmd == "setup" ]]; then
    ./scripts/setup.sh
elif [[ $cmd == "teardown" ]]; then
    ./scripts/teardown.sh
elif [[ $cmd == "restart" ]]; then
    ./scripts/teardown.sh && ./scripts/setup.sh
elif [[ $cmd == "help" ]]; then
    usage
    exit 0
else
    echo "Unknown Option $cmd"
    echo
    usage
    exit 1
fi
