#!/bin/env bash
set -e
# set -v # verbosity for debugging
set -o pipefail

function usage {
    cat <<EOF
Run an Aries agent with below options.
Usage:
    -p, --port [number]:
        REQUIRED: port number at which to operate
    -a, --auditor:
        Runs only the auditor and no Aries logic, can only be run in combination with the port flag.
    -n, --name [string]:
        Name of the Agent type to be run
    --multitenant:
        Enables support for multinenacy, i.e., holding walltes for sub-agents.
    -h, --help:
        Print help/usage
EOF
}

# Set flag variables
MULTITENANT=0
AUDITOR=0
# Docker specific variables
DOCKER_IMAGE_NAME="aries-my-agent"
RUN_MODE="docker"
DOCKERHOST=$(./scripts/getDockerHost.sh)
DOCKER_NETWORK="bridge" # bridge or host
# Aries/Indy specific variables
LEDGER_URL="http://$DOCKERHOST:9000"
GENESIS_URL="$LEDGER_URL/genesis"

while [[ $# -gt 0 ]]; do
    case $1 in
        -p | --port)
            PORT=$2
            # We define a portrange of +9 for each agent
            PORTRANGE="$2-$((PORT + 9))"
            shift
            shift
            ;;
        -a | --auditor)
            AUDITOR=1
            shift
            ;;
        -n | --name)
            AGENT_NAME=$2
            shift
            shift
            ;;
        --multitenant)
            MULTITENANT=1
            shift
            ;;
        -h | --help)
            usage
            exit 1
            ;;
        -*)
            echo "Unknown option $1"
            usage
            exit 1
            ;;
    esac
done

# Catch incompatible flags
if [[ $MULTITENANT == 1 && $AUDITOR == 1 ]]; then
    echo "invalid combination"
    usage
    exit 1
fi

DOCKER_FLAGS=(
    "--network=$DOCKER_NETWORK"
    "-p 0.0.0.0:$PORTRANGE:$PORTRANGE"
    "-e DOCKERHOST=$DOCKERHOST"
    "-e RUNMODE=$RUN_MODE"
)

if [[ $AUDITOR == 1 ]]; then
    # in case we have an auditor, we skip a lot of the default environments for the aries agents
    AGENT_NAME=auditor
else
    AGENT_NAME="agents.$AGENT_NAME"
    DOCKER_FLAGS+=(
        "-e LEDGER_URL=$LEDGER_URL"
        "-e GENESIS_URL=$GENESIS_URL"
        "-e POSTGRES=1"
    )
    ARIES_FLAGS=(
        "--wallet-type askar"
        "--did-exchange"
        "--reuse-connections"
        "--revocation"
        "--ident=$AGENT_NAME"
        "--port $PORT"
    )
    if [[ $MULTITENANT == 1 ]]; then
        ARIES_FLAGS+=("--multitenant")
    fi
fi

# we need to build each time, so changed files get copied over
docker build -t $DOCKER_IMAGE_NAME . || exit 1

# shellcheck disable=SC2048,SC2086
docker container run --rm -it \
    ${DOCKER_FLAGS[*]} \
    $DOCKER_IMAGE_NAME "$AGENT_NAME" \
    ${ARIES_FLAGS[*]}
